name: "sdTokens: Verify Reports"

on:
  workflow_dispatch:
    inputs:
      protocol:
        description: 'Protocol to check'
        required: true
        type: choice
        options:
        - curve
        - balancer
        - fxn
        - frax
        - pendle
        - cake
        default: 'curve'
  repository_dispatch:
    types: [trigger-reports-checker]

jobs:
  check-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.5.1"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Install node dependencies
        run: pnpm install

      - name: Set protocol value
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PROTOCOL=${{ github.event.inputs.protocol }}" >> $GITHUB_ENV
          else
            echo "PROTOCOL=curve" >> $GITHUB_ENV
          fi

      - name: Run reportVerifier script
        run: pnpm tsx script/repartition/sdTkns/reportVerifier.ts ${{ env.PROTOCOL }}
        env:
          TELEGRAM_VERIF_API_KEY: ${{ secrets.TELEGRAM_VERIF_API_KEY }}
          TELEGRAM_VERIF_CHAT_ID: ${{ secrets.TELEGRAM_VERIF_CHAT_ID }}
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY }}

      - name: Send error notification to Telegram
        if: failure()
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: -1002354704686
          token: ${{ secrets.TG_API_KEY_BOT_ERROR }}
          format: html
          message: |
            ‚ùå <b>Workflow failed</b>
            ‚Ä¢ <b>Workflow:</b> ${{ github.workflow }}
            ‚Ä¢ <b>Job:</b> check-reports
            ‚Ä¢ <b>Protocol:</b> ${{ env.PROTOCOL }}
            ‚Ä¢ <b>Trigger:</b> ${{ github.event_name }}
            ‚Ä¢ <b>Status:</b> ${{ job.status }}
            üìã <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View workflow logs</a>
